/* Exemplo 1 do slide */

options {
	STATIC = false;
}
PARSER_BEGIN (Adder)
public class Adder {
	public static void main (String args[])
		throws ParseException, TokenMgrError {
			Adder interpreter = new Adder(System.in);
			interpreter.Start();
		}

}
PARSER_END (Adder)

SKIP : { " " }
SKIP : { "\n" | "\r" | "\r\n" }
TOKEN : { < PLUS : "+" > }
TOKEN : { <NUMBER : (["0"-"9"])+ > }

void Start() :
{}
{
	<NUMBER>
	(
		<PLUS>
		<NUMBER>
	)*
	<EOF>
}
